# Generated by Django 2.2.5 on 2019-10-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acno', models.IntegerField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('blc', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
