# Generated by Django 2.2.5 on 2019-10-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='acno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='age',
            field=models.IntegerField(),
        ),
    ]
